name: plp_login_demo
description: "A new Flutter project."
publish_to: 'none' # If you don't want to publish the package, otherwise remove this line.
version: 0.1.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
 
